# Generated by Django 5.1.2 on 2024-10-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0002_user_city_user_country_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rate',
            name='place',
        ),
        migrations.AddField(
            model_name='rate',
            name='Latitude',
            field=models.CharField(default='', max_length=600),
        ),
        migrations.AddField(
            model_name='rate',
            name='Longitude',
            field=models.CharField(default='', max_length=600),
        ),
    ]
