# Generated by Django 5.1.2 on 2024-10-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0003_remove_rate_place_rate_latitude_rate_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='rate',
            field=models.IntegerField(default=1, max_length=5),
        ),
    ]
