# Generated by Django 5.1.2 on 2024-10-13 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0004_alter_rate_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='reason',
            field=models.CharField(default='', max_length=300),
        ),
    ]
