# Generated by Django 5.1.2 on 2024-10-13 17:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Maps', '0005_rate_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='favorite',
            field=models.ManyToManyField(related_name='favorited_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
